[package]
name = "cargo-espflash"
version = "0.1.4"
authors = [
    "Robin Appelman <robin@icewind.nl>",
    "Jesse Braham <jesse@beta7.io>",
]
edition = "2018"
description = "Cargo subcommand for flashing Espressif devices over serial"
repository = "https://github.com/esp-rs/espflash"
license = "GPL-2.0"
keywords = [
    "cargo",
    "cli",
    "embedded",
    "esp",
    "xtensa",
]
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::cargo-plugins",
    "embedded",
]

[dependencies]
miette = "2"
cargo_metadata = "0.14"
cargo_toml = "0.10"
clap = "2.33"
crossterm = "0.21"
espflash = { version = "*", path = "../espflash" }
guess_host_triple = "0.1"
serde = { version = "1.0", features = ["derive"] }
serial = "0.4"
toml = "0.5"
thiserror = "1"
