[package]
name = "espflash"
version = "0.1.1"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
license = "GPL-2.0"
description = "ESP8266 and ESP32 serial flasher"
repository = "https://github.com/icewind1991/espflash"

[[bin]]
name = "espflash"
path = "src/main.rs"

[lib]

[dependencies]
binread = "1.1.1"
bytemuck = { version = "1.4.0", features = ["derive"] }
main_error = "0.1.1"
md5 = "0.7.0"
pico-args = "0.3.4"
serial = "0.4"
sha2 = "0.9.1"
slip-codec =  "0.1.2"
thiserror = "1.0.20"
xmas-elf = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
directories-next = "1.0.1"

[dev-dependencies]
pretty_assertions = "0.6.1"
